# Generated by Django 3.2.13 on 2022-06-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('typeOfSoil', models.CharField(max_length=50)),
                ('soilProperties', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('landHistory', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLandLocator.land')),
            ],
        ),
    ]
