# Generated by Django 3.2.13 on 2022-06-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLandLocator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='landCode',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
