# Generated by Django 3.2.13 on 2022-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLandLocator', '0002_land_landcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='landCode',
            field=models.CharField(max_length=5),
        ),
    ]
