# Generated by Django 3.2.13 on 2022-07-12 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appLandLocator', '0003_alter_land_landcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='primaryImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
